# Intentionally weak TLS policy for AgileSec V1 demo.
min_protocol = TLSv1
max_protocol = TLSv1.1
ciphers = AES128-SHA:DES-CBC3-SHA:RC4-SHA
signature_algorithm = sha1WithRSAEncryption
certificate = ../certs/demo_sha1_self_signed.crt
private_key = ../certs/demo_rsa_1024_private_key.pem

